services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - /srv/files:/srv
      - filebrowser_db:/database
      - filebrowser_config:/config
    labels:
      - diun.enable=true

volumes:
  filebrowser_db:
  filebrowser_config:
