services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./diun:/data
    environment:
      - TZ=${TZ}
      - DIUN_PROVIDERS_DOCKER=${DIUN_PROVIDERS_DOCKER}
      - DIUN_WATCH_WORKERS=${DIUN_WATCH_WORKERS}
      - DIUN_WATCH_SCHEDULE=${DIUN_WATCH_SCHEDULE}
      - DIUN_NOTIF_DISCORD_WEBHOOKURL=${DIUN_DISCORD_WEBHOOK}
    restart: unless-stopped
