services:
  prometheus:
    image: prom/prometheus:v3.5.0
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9091:9090
    restart: unless-stopped
    extra_hosts:
      - "host.internal.docker:host-gateway"
    labels:
      - diun.enable=true

volumes:
  prometheus_data:
